docs:
  - changed-files:
      - any-glob-to-any-file: ["docs/*", "example/*", "**/*.md"]

packages:
  - changed-files:
      - any-glob-to-any-file: "packages/*"

dependencies:
  - changed-files:
      - any-glob-to-all-files: ["**/package.json", "pnpm-lock.yaml"]

workflows:
  - changed-files:
      - any-glob-to-any-file: ".github/**"
