version: '3.9'

services:
  es-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: es-elastic
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - "9200:9200"
    volumes:
      - type: tmpfs
        target: /usr/share/elasticsearch/data
