version: '3.3'

services:
  mongodb:
    container_name: es-mongodb
    image: mongo:7
    ports:
      - 27017:27017
    volumes:
      - type: tmpfs
        target: /data/db

  dynamodb:
    container_name: es-dynamodb
    image: amazon/dynamodb-local:latest
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    ports:
      - 8000:8000
    volumes:
      - type: tmpfs
        target: /home/dynamodblocal/data

  postgres:
    container_name: es-postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
