version: '3.3'

services:
  es-mongodb:
    container_name: es-mongo
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - type: tmpfs
        target: /data/db

  es-elastic:
    image: elasticsearch:8.2.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - type: tmpfs
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
