version: 2

aliases:
  - &restore-cache
    restore_cache:
        key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
  - &install-pnpm
    run:
      name: Install pnpm package manager
      command: |
        curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@7
        pnpm setup
  - &install-deps
    run:
        name: Install dependencies
        command: pnpm install
  - &save-cache
    save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
  - &build-packages
    run:
        name: Build
        command: npm run build

jobs:
  build:
    working_directory: ~/ocoda
    docker:
      - image: node:18
    steps:
      - checkout
      - *restore-cache
      - *install-pnpm
      - *install-deps
      - *save-cache
      - run:
          name: Build
          command: pnpm build

  test:
    working_directory: ~/ocoda
    machine: true
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - *restore-cache
      - *install-pnpm
      - run:
          name: Install Node
          command: pnpm env use --global 18
      - *install-deps
      - run:
          name: Prepare
          command: |
            docker-compose up -d
            sleep 10
      - run:
          name: List containers
          command: docker ps
      - run:
          name: linting and formatting
          command: pnpm ci
      - run:
          name: test
          command: pnpm ci

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
