name: CD Docs

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - docs/**

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build the documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup job
        id: setup-job
        uses: ./.github/setup-job
        with:
          cache-key: docs
          node-version: 22.x

      - name: Setup GH Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Build
        run: pnpm build --filter='./docs/**'

      - name: Upload build
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/dist

  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Publish to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
