name: CI Docs

on:
    workflow_dispatch:
    pull_request:
      branches: ['master']
      paths:
        - .github/ci-docs.yml
        - docs/**

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build docs

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup job environment
        id: setup-job
        uses: ./.github/actions/setup-job-env
        with:
          cache-key: docs
          node-version: 22.x

      - name: Build
        run: pnpm build --filter="./docs/**"

  test:
    needs: [build]
    runs-on: ubuntu-latest

    name: Test docs

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup job environment
        id: setup-job
        uses: ./.github/actions/setup-job-env
        with:
          cache-key: docs
          node-version: 22.x

      - name: Test linting, formatting and import sorting
        run: pnpm run ci --filter=@ocoda/event-sourcing-docs

  merge-check:
    needs: [build, test]
    uses: ./.github/workflows/merge-check.yml
    with:
        conditions: ${{ needs.test.result == 'success' }}